### ISSUE TITLE
Test runner fails (documentation issue?)

### ISSUE THREAD

**Issue by simon-brooke** [jahfer/clj-activitypub#1]
Hi

README says that `clj -X:test` will run the tests. In fact, what I'm seeing is:

```bash
illuminator:clj-activitypub simon$ clj -X:test
No function found on command line or in :exec-fn
```

I suspect your environment has some context which allows it to select the appropriate test runner, but as I almost always work in a Leiningen environment this is unfamiliar to me and I'm not able to guess it.

**Comment by jahfer** [comment]
Ah yep, the README is outdated. The project used to be a single lib but I split it into `activitypub-core` and `activitypub-ring` recently. There's no top-level test running anymore, so you'll need to `cd` into either of those directories and then run `clj -X:test`.

I'll update the README!

**Comment by jahfer** [comment]
https://github.com/jahfer/clj-activitypub#running-tests
